In [1]:
import numpy as np

## Datatypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [17]:
a2=np.array([[1,2.0,3.3],
            [4,5,6.5]])
a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [18]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [19]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
a1.shape

(3,)

In [21]:
a2.shape

(2, 3)

In [22]:
a3.shape

(2, 3, 3)

In [23]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [24]:
a3.ndim

3

In [25]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [26]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [27]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [28]:
# Create a dataframe from a Numpy array
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating Arrays

In [29]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [30]:
ones=np.ones((2,3))

In [31]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [34]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[9, 0, 2, 4, 3],
       [9, 1, 6, 3, 8],
       [1, 6, 6, 2, 3]])

In [35]:
random_array

array([[9, 0, 2, 4, 3],
       [9, 1, 6, 3, 8],
       [1, 6, 6, 2, 3]])

In [39]:
# Pseudo-random numbers
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Viewing arrays and matrices 64

In [40]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a1

array([1, 2, 3])

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [43]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [45]:
a3[:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [47]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

## Manipulating and comparing arrays

### Arithmetic

In [48]:
a1

array([1, 2, 3])

In [50]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [51]:
a1 + ones

array([2., 3., 4.])

In [52]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [53]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [54]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [55]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

### How to reshape a2 to be compatible with a3 and be able to multiply

In [56]:
a1 / ones

array([1., 2., 3.])

In [57]:
### floor division rounds down
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [58]:
### to the power
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [59]:
a1/2

array([0.5, 1. , 1.5])

In [60]:
a1%2

array([1, 0, 1], dtype=int32)

In [61]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [62]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation
Performing the same operation on a number of things

In [63]:
listy_list = [1,2,3]
type(listy_list)

list

In [64]:
sum(listy_list)

6

In [65]:
sum(a1)

6

In [66]:
np.sum(a1)

6

## Use Python's methods (sum) on Python datatypes and Numpy's methods (np.sum) on Numpy arrays

In [67]:
# Create a massive Numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [68]:
massive_array[:20]

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443,
       0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194])

In [69]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

18.3 ms ± 301 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
52.9 µs ± 1.21 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [70]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [71]:
mean(a2)

NameError: name 'mean' is not defined

In [72]:
np.mean(a2)

3.6333333333333333

In [73]:
np.max(a2)

6.5

In [74]:
np.std(a2)

1.8226964152656422

In [75]:
np.var(a2)

3.3222222222222224

In [76]:
np.sqrt(np.var(a2))

1.8226964152656422

## Reshaping and transposing

In [77]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [78]:
a2.shape

(2, 3)

In [79]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [80]:
a3.shape

(2, 3, 3)

In [82]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [84]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [85]:
# Transpose swap the axis
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [86]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

## Dot product

In [87]:
np.random.seed(0)

mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [88]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [89]:
# Element wise multiplication (Hadamard product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [90]:
# Dot product
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [91]:
mat2.T

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [93]:
mat3 = np.dot(mat1 , mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [94]:
mat3.shape

(5, 5)

## Dot product example (nut butter sales)

In [95]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [96]:
# Create weekly sales dataframe
weekly_sales = pd.DataFrame(sales_amounts,
                           index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                           columns=["Almond","Peanut", "Cashues"])
weekly_sales

Almond  Peanut  Cashues
Mon        12      15        0
Tues        3       3        7
Wed         9      19       18
Thurs       4       6       12
Fri         1       6        7

In [97]:
# Create prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [99]:
# Create prices dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3),
                           index=["Price"],
                           columns=["Almond","Peanut", "Cashues"])
butter_prices

Almond  Peanut  Cashues
Price      10       8       12

In [100]:
total_sales = prices.dot(sales_amounts.T)

In [101]:
total_sales

array([240, 138, 458, 232, 142])

In [105]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [106]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond  Peanut  Cashues  Total ($)
Mon        12      15        0        240
Tues        3       3        7        138
Wed         9      19       18        458
Thurs       4       6       12        232
Fri         1       6        7        142